project:
  type: website

website:
  title: "giordano_rogers"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/giordanorogers
      - icon: youtube
        href: https://www.youtube.com/@giordanorogers
format:
  html:
    theme: 
      - cyborg
      - custom.scss
    css: styles.css
    fontsize: 1.3em
    monofont: Courier
    highlight-style: github-dark



